# Generated by Django 4.2.19 on 2025-03-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
