# Generated by Django 4.2.19 on 2025-03-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
